apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: nodejs-reference-architecture
  annotations:
    github.com/project-slug: diegotroitino/nodejs-reference-architecture
spec:
  type: reference-architecture
  lifecycle: experimental
  owner: diego.troitino
