apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pino-sample
  annotations:
    github.com/project-slug: diegotroitino/nodejs-reference-architecture
spec:
  type: other
  lifecycle: unknown
  owner: diego.troitino
